# This is a basic workflow to help you get started with Actions

name: api-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    paths:
      - '.github/workflows/api-build.yml'
      - 'api/**'
  workflow_dispatch: #manually triggered
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build-dotnet-api
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Enable PowerShell scripts for this run
          shell: pwsh
          run: |
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        - uses: actions/checkout@v4
        - run: dotnet --list-runtimes
        - run: dotnet --list-sdks
        - run: dotnet build
          working-directory: ./api
        # Runs a single command using the runners she

       